# Generated by Django 2.2.3 on 2019-07-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenceflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('scenceid', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'scenceflow',
                'unique_together': {('scenceid', 'datetime', 'num')},
            },
        ),
    ]
