# Generated by Django 2.2.3 on 2019-08-14 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid')),
                ('adjectives', models.CharField(db_column='adjectives', max_length=16, verbose_name='形容词')),
                ('rate', models.FloatField(db_column='rate', verbose_name='评分')),
            ],
            options={
                'db_table': 'comment_rate',
            },
        ),
        migrations.CreateModel(
            name='Geographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', db_index=True, verbose_name='标识')),
                ('longitude', models.FloatField(db_column='longitude', verbose_name='经度')),
                ('latitude', models.CharField(db_column='latitude', max_length=18, verbose_name='维度')),
                ('flag', models.SmallIntegerField(db_column='flag', verbose_name='类别标识flag(百度数据为1，腾讯为0')),
            ],
            options={
                'db_table': 'geographic',
            },
        ),
        migrations.CreateModel(
            name='NetComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid', db_index=True)),
                ('commentuser', models.CharField(db_column='commentuser', max_length=32, verbose_name='网友')),
                ('comment', models.TextField(db_column='comment', verbose_name='评论')),
                ('commenttime', models.DateField(db_column='commenttime', verbose_name='评论时间')),
                ('commentlike', models.SmallIntegerField(db_column='commentlike', verbose_name='星级好感数（1-5）')),
                ('userphoto', models.ImageField(db_column='userphoto', upload_to='user', verbose_name='网友头像')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition0',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition1',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition2',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition3',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition4',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition5',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition6',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition7',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('lon', models.FloatField(db_column='lon', verbose_name='经度')),
                ('lat', models.FloatField(db_column='lat', verbose_name='纬度')),
                ('num', models.SmallIntegerField(db_column='num', verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition9',
            },
        ),
        migrations.CreateModel(
            name='ScenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('photo', models.ImageField(upload_to='photo')),
            ],
            options={
                'db_table': 'photodb',
            },
        ),
        migrations.CreateModel(
            name='ScenceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(db_column='longitude', verbose_name='中心经度')),
                ('latitude', models.FloatField(db_column='latitude', verbose_name='中心纬度')),
                ('loaction', models.CharField(db_column='loaction', max_length=18, verbose_name='所处城市')),
                ('citypid', models.IntegerField(db_column='citypid', verbose_name='所处城市标识')),
                ('weatherpid', models.TextField(db_column='weatherpid', verbose_name='对应的天气标识')),
                ('flag', models.SmallIntegerField(db_column='flag', verbose_name='类别标识,百度数据为1，腾讯为0')),
                ('province', models.CharField(db_column='province', max_length=18, verbose_name='省份')),
            ],
            options={
                'db_table': 'scencemanager',
            },
        ),
        migrations.CreateModel(
            name='ScenceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid')),
                ('trafficstate', models.CharField(db_column='trafficstate', max_length=16, verbose_name='交通状况')),
                ('weatherstate', models.CharField(db_column='weatherstate', max_length=16, verbose_name='天气状况')),
                ('coststate', models.CharField(db_column='coststate', max_length=16, verbose_name='性价比状况')),
                ('environmentstate', models.CharField(db_column='environmentstate', max_length=16, verbose_name='环境状况')),
            ],
            options={
                'db_table': 'scencestate',
            },
        ),
        migrations.CreateModel(
            name='SearchRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', db_index=True, verbose_name='标识')),
                ('tmp_date', models.IntegerField(db_column='tmp_date', verbose_name='时间,格式为yyyymmdd')),
                ('area', models.CharField(db_column='area', max_length=32, verbose_name='地名')),
                ('rate', models.IntegerField(db_column='rate', verbose_name='频率')),
                ('name', models.CharField(db_column='name', max_length=16, verbose_name='搜索引擎，包括微信-wechat，百度-baidu，搜狗-sougou')),
                ('flag', models.SmallIntegerField(db_column='flag', default=0, verbose_name='种类')),
            ],
            options={
                'db_table': 'searchrate',
            },
        ),
        migrations.CreateModel(
            name='TableManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('last_date', models.IntegerField(verbose_name='最近更新时间--时间戳，根据时间戳查找数据')),
                ('table_id', models.SmallIntegerField(verbose_name='对应表格标识，表格标识为0-9')),
                ('flag', models.SmallIntegerField(db_column='flag', verbose_name='类别标识flag(百度数据为1，腾讯为0')),
            ],
            options={
                'db_table': 'tablemanager',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idcard', models.BigIntegerField(db_column='idcard', verbose_name='身份证')),
                ('photo', models.ImageField(null=True, upload_to='user')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'userdb',
            },
        ),
        migrations.CreateModel(
            name='ScenceTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('ddate', models.IntegerField(db_column='ddate', verbose_name='日期,格式为yyyymmdd')),
                ('ttime', models.TimeField(db_column='ttime', verbose_name='时间,格式为HH：MM：SS')),
                ('rate', models.FloatField(db_column='rate', verbose_name='频率')),
            ],
            options={
                'db_table': 'scencetrend',
                'index_together': {('pid', 'ddate', 'ttime', 'rate')},
            },
        ),
        migrations.CreateModel(
            name='ScenceFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('ddate', models.IntegerField(db_column='ddate', verbose_name='日期,格式为yyyymmdd')),
                ('ttime', models.TimeField(db_column='ttime', verbose_name='时间,格式为HH：MM：SS')),
                ('num', models.IntegerField(db_column='num', verbose_name='总人数')),
            ],
            options={
                'db_table': 'scenceflow',
                'index_together': {('pid', 'ddate', 'ttime', 'num')},
            },
        ),
    ]
