# Generated by Django 2.2.3 on 2019-07-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scenceflow',
        ),
    ]
