# Generated by Django 2.2.3 on 2019-07-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_scencemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_index=True, verbose_name='标识')),
                ('tmp_date', models.IntegerField(verbose_name='时间,格式为yyyymmdd')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('rate', models.IntegerField(verbose_name='频率')),
                ('name', models.CharField(max_length=16, verbose_name='搜索引擎，包括微信-wechat，百度-baidu，搜狗-sougou')),
            ],
            options={
                'db_table': 'searchrate',
            },
        ),
        migrations.AlterField(
            model_name='scenceflow',
            name='ddate',
            field=models.IntegerField(verbose_name='日期,格式为yyyymmdd'),
        ),
        migrations.AlterField(
            model_name='scenceflow',
            name='ttime',
            field=models.TimeField(verbose_name='时间,格式为HH：MM：SS'),
        ),
    ]
