# Generated by Django 2.2.3 on 2019-08-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20190823_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictParamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid', verbose_name='景区标识')),
                ('flag', models.BooleanField(db_column='flag', verbose_name='是否为重大节假日，是的话为1')),
                ('hconstant', models.FloatField(db_column='hconstant', verbose_name='最高项系数')),
                ('hpower', models.SmallIntegerField(db_column='hpower', verbose_name='最高次幂')),
                ('sconstant', models.FloatField(db_column='sconstant', verbose_name='二次项系数')),
                ('spower', models.SmallIntegerField(db_column='spower', verbose_name='二次次幂')),
                ('lconstant', models.FloatField(db_column='lconstant', verbose_name='一次项系数')),
                ('lpower', models.SmallIntegerField(db_column='lpower', verbose_name='一次次幂')),
                ('mconstant', models.FloatField(db_column='mconstant', verbose_name=' 常数项')),
            ],
            options={
                'db_table': 'predictmodel',
            },
        ),
    ]
