# Generated by Django 2.2.3 on 2019-07-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0003_auto_20190723_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_index=True, verbose_name='标识')),
                ('latitude', models.FloatField(verbose_name='中心纬度')),
                ('loaction', models.CharField(max_length=18, verbose_name='所处城市')),
            ],
            options={
                'db_table': 'geographic',
            },
        ),
    ]
