# Generated by Django 2.2.3 on 2019-07-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0004_geographic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenceTrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('ddate', models.IntegerField(verbose_name='日期,格式为yyyymmdd')),
                ('ttime', models.TimeField(verbose_name='时间,格式为HH：MM：SS')),
                ('rate', models.FloatField(verbose_name='频率')),
            ],
            options={
                'db_table': 'scencetrend',
                'unique_together': {('pid', 'ddate', 'ttime', 'rate')},
            },
        ),
    ]
