# Generated by Django 2.2.3 on 2019-07-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0005_scencetrend'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('last_date', models.IntegerField(verbose_name='最近更新时间,根据最新时间查找数据')),
                ('table_id', models.SmallIntegerField(verbose_name='对应表格标识，表格标识为0-9')),
            ],
            options={
                'db_table': 'tablemanager',
            },
        ),
    ]
