# Generated by Django 2.2.3 on 2019-07-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0006_tablemanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeoplePosition0',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition0',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition1',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition2',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition3',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition4',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition5',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition6',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition7',
            },
        ),
        migrations.CreateModel(
            name='PeoplePosition8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(verbose_name='标识')),
                ('area', models.CharField(max_length=32, verbose_name='地名')),
                ('longitude', models.FloatField(verbose_name='经度')),
                ('latitude', models.FloatField(verbose_name='纬度')),
                ('num', models.SmallIntegerField(verbose_name='人数')),
            ],
            options={
                'db_table': 'peopleposition9',
            },
        ),
    ]
