# Generated by Django 2.2.3 on 2019-07-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0008_scencemanager_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peopleposition0',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition0',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition1',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition1',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition2',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition2',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition3',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition3',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition4',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition4',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition5',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition5',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition6',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition6',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition7',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition7',
            old_name='longitude',
            new_name='lon',
        ),
        migrations.RenameField(
            model_name='peopleposition8',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='peopleposition8',
            old_name='longitude',
            new_name='lon',
        ),
    ]
