# Generated by Django 2.2.3 on 2019-07-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0009_auto_20190723_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographic',
            name='loaction',
        ),
        migrations.AddField(
            model_name='geographic',
            name='longitude',
            field=models.FloatField(db_column='longitude', default=1, verbose_name='中心纬度'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='geographic',
            name='latitude',
            field=models.CharField(db_column='latitude', max_length=18, verbose_name='所处城市'),
        ),
        migrations.AlterField(
            model_name='geographic',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', db_index=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition0',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition0',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition0',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition0',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition0',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition1',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition1',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition1',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition1',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition1',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition2',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition2',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition2',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition2',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition2',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition3',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition3',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition3',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition3',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition3',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition4',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition4',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition4',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition4',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition4',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition5',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition5',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition5',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition5',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition5',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition6',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition6',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition6',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition6',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition6',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition7',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition7',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition7',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition7',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition7',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='peopleposition8',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='peopleposition8',
            name='lat',
            field=models.FloatField(db_column='lat', verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='peopleposition8',
            name='lon',
            field=models.FloatField(db_column='lon', verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='peopleposition8',
            name='num',
            field=models.SmallIntegerField(db_column='num', verbose_name='人数'),
        ),
        migrations.AlterField(
            model_name='peopleposition8',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='scenceflow',
            name='ddate',
            field=models.IntegerField(db_column='ddate', verbose_name='日期,格式为yyyymmdd'),
        ),
        migrations.AlterField(
            model_name='scenceflow',
            name='num',
            field=models.IntegerField(db_column='num', verbose_name='总人数'),
        ),
        migrations.AlterField(
            model_name='scenceflow',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='scenceflow',
            name='ttime',
            field=models.TimeField(db_column='ttime', verbose_name='时间,格式为HH：MM：SS'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='citypid',
            field=models.IntegerField(db_column='citypid', verbose_name='所处城市标识'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='flag',
            field=models.SmallIntegerField(db_column='flag', verbose_name='类别标识,百度数据为1，腾讯为0'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='latitude',
            field=models.FloatField(db_column='latitude', verbose_name='中心纬度'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='loaction',
            field=models.CharField(db_column='loaction', max_length=18, verbose_name='所处城市'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='longitude',
            field=models.FloatField(db_column='longitude', verbose_name='中心经度'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='province',
            field=models.CharField(db_column='province', max_length=18, verbose_name='省份'),
        ),
        migrations.AlterField(
            model_name='scencemanager',
            name='weatherpid',
            field=models.TextField(db_column='weatherpid', verbose_name='对应的天气标识'),
        ),
        migrations.AlterField(
            model_name='scencetrend',
            name='ddate',
            field=models.IntegerField(db_column='ddate', verbose_name='日期,格式为yyyymmdd'),
        ),
        migrations.AlterField(
            model_name='scencetrend',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='scencetrend',
            name='rate',
            field=models.FloatField(db_column='rate', verbose_name='频率'),
        ),
        migrations.AlterField(
            model_name='scencetrend',
            name='ttime',
            field=models.TimeField(db_column='ttime', verbose_name='时间,格式为HH：MM：SS'),
        ),
        migrations.AlterField(
            model_name='searchrate',
            name='area',
            field=models.CharField(db_column='area', max_length=32, verbose_name='地名'),
        ),
        migrations.AlterField(
            model_name='searchrate',
            name='name',
            field=models.CharField(db_column='name', max_length=16, verbose_name='搜索引擎，包括微信-wechat，百度-baidu，搜狗-sougou'),
        ),
        migrations.AlterField(
            model_name='searchrate',
            name='pid',
            field=models.SmallIntegerField(db_column='pid', db_index=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='searchrate',
            name='rate',
            field=models.IntegerField(db_column='rate', verbose_name='频率'),
        ),
        migrations.AlterField(
            model_name='searchrate',
            name='tmp_date',
            field=models.IntegerField(db_column='tmp_date', verbose_name='时间,格式为yyyymmdd'),
        ),
    ]
