# Generated by Django 2.2.3 on 2019-07-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0010_auto_20190723_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geographic',
            name='latitude',
            field=models.CharField(db_column='latitude', max_length=18, verbose_name='维度'),
        ),
        migrations.AlterField(
            model_name='geographic',
            name='longitude',
            field=models.FloatField(db_column='longitude', verbose_name='经度'),
        ),
    ]
