# Generated by Django 2.2.3 on 2019-07-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0012_auto_20190724_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablemanager',
            name='flag',
            field=models.SmallIntegerField(db_column='flag', default=1, verbose_name='类别标识flag(百度数据为1，腾讯为0'),
            preserve_default=False,
        ),
    ]
