# Generated by Django 2.2.3 on 2019-07-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0013_tablemanager_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='geographic',
            name='flag',
            field=models.SmallIntegerField(db_column='flag', default=1, verbose_name='类别标识flag(百度数据为1，腾讯为0'),
            preserve_default=False,
        ),
    ]
