# Generated by Django 2.2.3 on 2019-07-25 08:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attractions', '0015_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='UserProfile',
        ),
    ]
