# Generated by Django 2.2.3 on 2019-07-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0017_imagemanager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageManager',
            new_name='ImageProfile',
        ),
    ]
