# Generated by Django 2.2.3 on 2019-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0018_auto_20190725_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprofile',
            name='price',
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='pid',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageprofile',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
