# Generated by Django 2.2.3 on 2019-07-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0019_auto_20190725_2143'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imageprofile',
            table='imagedb',
        ),
    ]
