# Generated by Django 2.2.3 on 2019-07-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0020_auto_20190725_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
