# Generated by Django 2.2.3 on 2019-07-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0022_auto_20190726_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(null=True, upload_to='user'),
        ),
    ]
