# Generated by Django 2.2.3 on 2019-07-26 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0023_auto_20190726_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageProfile',
        ),
    ]
