# Generated by Django 2.2.3 on 2019-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0024_delete_imageprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('photo', models.ImageField(upload_to='photo')),
            ],
            options={
                'db_table': 'photodb',
            },
        ),
    ]
