# Generated by Django 2.2.3 on 2019-08-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0026_commentrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrate',
            name='flag',
            field=models.IntegerField(db_column='flag', default=0, verbose_name='种类'),
        ),
    ]
