# Generated by Django 2.2.3 on 2019-08-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0027_searchrate_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrate',
            name='flag',
            field=models.SmallIntegerField(db_column='flag', default=0, verbose_name='种类'),
        ),
    ]
