# Generated by Django 2.2.3 on 2019-08-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0028_auto_20190811_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid')),
                ('commentuser', models.CharField(db_column='commentuser', max_length=32, verbose_name='网友')),
                ('comment', models.TextField(db_column='comment', verbose_name='评论')),
                ('commenttime', models.DateField(db_column='commenttime', verbose_name='评论时间')),
                ('commentlike', models.SmallIntegerField(db_column='commentlike', verbose_name='星级好感数（1-5）')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
