# Generated by Django 2.2.3 on 2019-08-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0028_auto_20190811_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid', db_index=True)),
                ('commentuser', models.CharField(db_column='commentuser', max_length=32, verbose_name='网友')),
                ('comment', models.TextField(db_column='comment', verbose_name='评论')),
                ('commenttime', models.DateField(db_column='commenttime', verbose_name='评论时间')),
                ('commentlike', models.SmallIntegerField(db_column='commentlike', verbose_name='星级好感数（1-5）')),
                ('userphoto', models.ImageField(upload_to='user', verbose_name='网友头像')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='ScenceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(db_column='pid', db_index=True)),
                ('trafficstate', models.CharField(db_column='trafficstate', max_length=16, verbose_name='交通状况')),
                ('weatherstate', models.CharField(db_column='weatherstate', max_length=16, verbose_name='天气状况')),
                ('coststate', models.CharField(db_column='coststate', max_length=16, verbose_name='性价比状况')),
                ('environmentstate', models.CharField(db_column='environmentstate', max_length=16, verbose_name='环境状况')),
            ],
            options={
                'db_table': 'scencestate',
            },
        ),
    ]
