# Generated by Django 2.2.3 on 2019-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0029_netcomment_scencestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netcomment',
            name='userphoto',
            field=models.ImageField(db_column='userphoto', upload_to='user', verbose_name='网友头像'),
        ),
    ]
