# Generated by Django 2.2.3 on 2019-08-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0029_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pid',
            field=models.IntegerField(db_column='pid', db_index=True),
        ),
    ]
