# Generated by Django 2.2.3 on 2019-08-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0030_auto_20190812_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scencestate',
            name='pid',
            field=models.IntegerField(db_column='pid'),
        ),
    ]
