# Generated by Django 2.2.3 on 2019-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0031_auto_20190812_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrate',
            name='num',
            field=models.SmallIntegerField(db_column='num', default=1, verbose_name='第几条'),
            preserve_default=False,
        ),
    ]
