# Generated by Django 2.2.3 on 2019-08-12 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0032_commentrate_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentrate',
            name='num',
        ),
    ]
