# Generated by Django 2.2.3 on 2019-08-15 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('appname', models.CharField(db_column='name', max_length=32, verbose_name='app名字')),
            ],
            options={
                'db_table': 'appinfo',
            },
        ),
        migrations.CreateModel(
            name='MobileBrand',
            fields=[
                ('id', models.SmallIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='品牌标识主键')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='品牌名')),
            ],
            options={
                'db_table': 'mobilebrand',
            },
        ),
        migrations.CreateModel(
            name='MobileSystemVersion',
            fields=[
                ('id', models.SmallIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='系统版本标识id')),
                ('version', models.CharField(db_column='version', max_length=18, verbose_name='系统版本')),
                ('category', models.CharField(db_column='category', max_length=5, verbose_name='系统归属（苹果，安卓）')),
            ],
            options={
                'db_table': 'mobilesystemversion',
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.SmallIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='网络标识')),
                ('name', models.CharField(db_column='name', max_length=4, verbose_name='网络名（3G,4G.5G,WIFI..）')),
            ],
            options={
                'db_table': 'network',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.SmallIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='标识')),
                ('name', models.CharField(db_column='name', max_length=18, verbose_name='运营商名')),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('installnum', models.SmallIntegerField(db_column='installnum', verbose_name='人均安装应用')),
                ('activenum', models.SmallIntegerField(db_column='activenum', verbose_name='人均安装应用')),
            ],
            options={
                'db_table': 'userhabit',
            },
        ),
        migrations.CreateModel(
            name='SexShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('boy', models.FloatField(db_column='boy', verbose_name='男生占比')),
                ('girl', models.FloatField(db_column='girl', verbose_name='男生占比')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.AppInfo', verbose_name='app标识')),
            ],
            options={
                'db_table': 'sexshare',
            },
        ),
        migrations.CreateModel(
            name='OperatorRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='运营商占有率')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.Operator', verbose_name='标识')),
            ],
            options={
                'db_table': 'operatorrate',
            },
        ),
        migrations.CreateModel(
            name='NetworkShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='网络占有率')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.Network', verbose_name='网络标识')),
            ],
            options={
                'db_table': 'networkshare',
            },
        ),
        migrations.CreateModel(
            name='MobileSystemRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='手机系统占有率')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.MobileSystemVersion', verbose_name='系统版本标识')),
            ],
            options={
                'db_table': 'mobilesystemrate',
            },
        ),
        migrations.CreateModel(
            name='BrandShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='品牌占有率')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.MobileBrand', verbose_name='品牌标识外键')),
            ],
            options={
                'db_table': 'brandshare',
            },
        ),
        migrations.CreateModel(
            name='AppProvinceShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('province', models.CharField(max_length=16, verbose_name='province')),
                ('rate', models.FloatField(db_column='rate', verbose_name='省份占有率')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.AppInfo', verbose_name='app标识')),
            ],
            options={
                'db_table': 'app_province_share',
            },
        ),
        migrations.CreateModel(
            name='AppLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('keyword', models.CharField(max_length=32, verbose_name='keyword')),
                ('rate', models.FloatField(db_column='rate', verbose_name='应用偏好占有率')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.AppInfo', verbose_name='app标识')),
            ],
            options={
                'db_table': 'applike',
            },
        ),
        migrations.CreateModel(
            name='AppActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('activenum', models.IntegerField(db_column='activenum', verbose_name='活跃数')),
                ('activerate', models.FloatField(db_column='activerate', verbose_name='活跃度')),
                ('base_activerate', models.FloatField(db_column='base_activerate', verbose_name='行业活跃度基准值')),
                ('aver_activerate', models.FloatField(db_column='aver_activerate', verbose_name='行业活跃度均值')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.AppInfo', verbose_name='app标识')),
            ],
            options={
                'db_table': 'appactive',
            },
        ),
        migrations.CreateModel(
            name='AgeShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('under_nineth', models.FloatField(db_column='under_nineth', verbose_name='19岁以下占比')),
                ('nin_twen', models.FloatField(db_column='nin_twen', verbose_name='19-25岁占比')),
                ('twe_thir', models.FloatField(db_column='twe_thir', verbose_name='26-35岁占比')),
                ('thir_four', models.FloatField(db_column='thir_four', verbose_name='36-45岁占比')),
                ('four_fift', models.FloatField(db_column='four_fift', verbose_name='46-55岁占比')),
                ('over_fift', models.FloatField(db_column='over_fift', verbose_name='55岁以上占比')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.AppInfo', verbose_name='app标识')),
            ],
            options={
                'db_table': 'ageshare',
            },
        ),
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpid', models.SmallIntegerField(db_column='mpid', verbose_name='机型标识')),
                ('mmodel', models.CharField(db_column='mmodel', max_length=32, verbose_name='机型')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='机型占有率')),
                ('brandtype', models.CharField(db_column='brandtype', max_length=8, verbose_name='品牌分类:安卓，苹果')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.MobileBrand', verbose_name='品牌标识外键')),
            ],
            options={
                'db_table': 'mobilemodel',
                'index_together': {('mpid', 'pid')},
            },
        ),
    ]
