# Generated by Django 2.2.3 on 2019-07-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', unique=True, verbose_name='品牌标识主键')),
                ('name', models.CharField(db_column='name', max_length=32, verbose_name='品牌名')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='品牌占有率')),
            ],
            options={
                'db_table': 'mobilebrand',
            },
        ),
        migrations.CreateModel(
            name='MobileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mpid', models.SmallIntegerField(db_column='mpid', verbose_name='机型标识')),
                ('mmodel', models.CharField(db_column='mmodel', max_length=32, verbose_name='机型')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='机型占有率')),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='internet.MobileBrand', to_field='pid', verbose_name='品牌标识外键')),
            ],
            options={
                'db_table': 'mobilemodel',
            },
        ),
    ]
