# Generated by Django 2.2.3 on 2019-08-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilebrand',
            name='flag',
            field=models.BooleanField(db_column='flag', default=0, verbose_name='是否公开'),
            preserve_default=False,
        ),
    ]
