# Generated by Django 2.2.3 on 2019-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemodel',
            name='mpid',
            field=models.SmallIntegerField(db_column='mpid', db_index=True, unique=True, verbose_name='机型标识'),
        ),
    ]
