# Generated by Django 2.2.3 on 2019-07-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0002_auto_20190726_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobileystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('version', models.CharField(db_column='version', max_length=32, verbose_name='类型名')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='占有率')),
            ],
            options={
                'db_table': 'mobilesystem',
            },
        ),
        migrations.CreateModel(
            name='NetWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('version', models.CharField(db_column='version', max_length=32, verbose_name='类型名')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='占有率')),
            ],
            options={
                'db_table': 'network',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('version', models.CharField(db_column='version', max_length=32, verbose_name='类型名')),
                ('ddate', models.DateField(db_column='ddate', verbose_name='日期')),
                ('rate', models.FloatField(db_column='rate', verbose_name='占有率')),
            ],
            options={
                'db_table': 'operator',
            },
        ),
    ]
