# Generated by Django 2.2.3 on 2019-07-26 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0003_mobileystem_network_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHabit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField(db_column='ddate')),
                ('installnum', models.SmallIntegerField(db_column='installnum')),
                ('activenum', models.SmallIntegerField(db_column='activenum')),
            ],
            options={
                'db_table': 'userhabit',
            },
        ),
    ]
