# Generated by Django 2.2.3 on 2019-07-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0004_userhabit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilebrand',
            name='ddate',
        ),
        migrations.RemoveField(
            model_name='mobilebrand',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='mobilebrand',
            name='rate',
        ),
        migrations.AlterField(
            model_name='mobilebrand',
            name='id',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False, unique=True, verbose_name='品牌标识主键'),
        ),
        migrations.DeleteModel(
            name='MobileModel',
        ),
    ]
