# Generated by Django 2.2.3 on 2019-07-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0005_auto_20190728_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilebrand',
            name='id',
            field=models.SmallIntegerField(db_column='id', primary_key=True, serialize=False, unique=True, verbose_name='品牌标识主键'),
        ),
    ]
