# Generated by Django 2.2.3 on 2019-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_roadtraffic_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citypid', models.IntegerField(db_column='pid', verbose_name='城市标识')),
                ('flag', models.BooleanField(db_column='flag', verbose_name='判断是否为最新数据')),
                ('aqi', models.SmallIntegerField(db_column='aqi', verbose_name='AQI ')),
                ('lasttime', models.DateTimeField(db_column='lasttime', verbose_name='最近更新时间')),
                ('pm2', models.SmallIntegerField(db_column='pm2', verbose_name='PM2.5/1h')),
                ('pm10', models.SmallIntegerField(db_column='pm10', verbose_name='PM10/1h')),
                ('co', models.FloatField(db_column='co', verbose_name='CO/1h')),
                ('no2', models.SmallIntegerField(db_column='no2', verbose_name='NO2/1h')),
                ('o3', models.SmallIntegerField(db_column='o3', verbose_name='O3/8h')),
                ('so2', models.SmallIntegerField(db_column='so2', verbose_name='SO2/1h')),
            ],
            options={
                'db_table': 'airstate',
            },
        ),
    ]
