# Generated by Django 2.2.3 on 2019-07-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_auto_20190724_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadtraffic',
            name='roadid',
            field=models.SmallIntegerField(db_column='roadid', default=0, verbose_name='道路标识'),
            preserve_default=False,
        ),
    ]
