# Generated by Django 2.2.3 on 2019-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_airstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airstate',
            name='flag',
            field=models.BooleanField(db_column='flag', verbose_name='判断是否为最新数据，1是，0否'),
        ),
    ]
