# Generated by Django 2.2.3 on 2019-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0004_roadtraffic_roadid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='标识')),
                ('city', models.CharField(db_column='city', max_length=32, verbose_name='城市名字')),
                ('up_date', models.IntegerField(db_column='up_date', verbose_name='更新时间，内容为时间戳')),
                ('roadid', models.SmallIntegerField(db_column='roadid', verbose_name='道路标识')),
            ],
            options={
                'db_table': 'roadmanager',
            },
        ),
    ]
