# Generated by Django 2.2.3 on 2019-08-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(db_column='rid', verbose_name='用户提交时随机产生一个id，用于下载文件的凭证')),
                ('file', models.FileField(db_column='file', upload_to='pdf')),
            ],
            options={
                'db_table': 'pdfdb',
            },
        ),
    ]
