# Generated by Django 2.2.3 on 2019-08-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainterface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdffile',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='id',
            field=models.UUIDField(db_column='id', editable=False, primary_key=True, serialize=False, verbose_name='用户提交时唯一产生uuid，用于下载文件的凭证'),
        ),
    ]
