# Generated by Django 2.2.3 on 2019-08-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datainterface', '0002_auto_20190824_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherManager',
            fields=[
                ('id', models.SmallIntegerField(db_column='id', primary_key=True, serialize=False, verbose_name='地区唯一标识')),
                ('city', models.CharField(db_column='city', max_length=32, verbose_name='城市名')),
            ],
            options={
                'db_table': 'weathermanager',
            },
        ),
        migrations.CreateModel(
            name='WeatherDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.SmallIntegerField(db_column='pid', verbose_name='地区标识')),
                ('ddate', models.IntegerField(db_column='ddate', verbose_name='日期')),
                ('weatherstate', models.CharField(db_column='weatherstate', max_length=32, verbose_name='天气情况')),
                ('template', models.CharField(db_column='template', max_length=32, verbose_name='温度')),
                ('wind', models.CharField(db_column='wind', max_length=32, verbose_name='风力')),
            ],
            options={
                'db_table': 'weatherdb',
                'index_together': {('pid', 'ddate')},
            },
        ),
    ]
